Removing outdated info about branch for Helm 2.
helm/helm-www pull request #1049
Opened 2021-03-17 10:04 UTC by bridgetkromhout

We no longer produce new releases for Helm 2 as of Nov 2020, so I'm removing the outdated directions for patching the `dev-v2` branch.

Signed-off-by: Bridget Kromhout <bridget@kromhout.org>

2021-03-18 08:33 UTC, hickeyma requested changes
Nearly there @bridgetkromhout. Just wondering should this doc be updated also: https://github.com/helm/helm-www/blob/master/content/zh/docs/community/developers.md ?

2021-03-18 18:03 UTC, bridgetkromhout commented
@hickeyma yes, but as a specific person is actively working on those docs, I mentioned it in https://github.com/helm/helm-www/pull/1048#discussion_r595933571 and got an affirmative answer. They have consistently updated the `zh` docs as the `en` ones have changed, too.

2021-03-18 20:50 UTC, hickeyma approved these changes
As per the explanation in https://github.com/helm/helm-www/pull/1049#issuecomment-802170060, it LGTM. Thanks @bridgetkromhout.

2021-03-19 16:29 UTC, flynnduism approved these changes

2021-03-26 18:22 UTC, merged