add bitnami repo
helm/helm-www pull request #1148
Opened 2021-07-02 10:05 UTC by woodgear

2021-07-02 12:21 UTC, iflan7744 approved these changes

2021-07-06 22:18 UTC, bridgetkromhout commented
Hi, @woodgear - thanks for this edit to the German-language translation of the "using helm" page. Can you please also make this change to the English page at https://github.com/helm/helm-www/blob/main/content/en/docs/intro/using_helm.md ? (Other languages are okay too, but we want to make sure the English page gets any essential clarifications, since people creating new translations are likely starting there.) Thanks!

2021-07-07 21:28 UTC, bacongobbler requested changes

2021-07-07 21:28 UTC, bacongobbler commented on content/de/docs/intro/using_helm.md
> +$ helm repo update
The call to `helm repo update` after a `helm repo add` is redundant. Would you mind removing this?

2021-12-02 20:52 UTC, bridgetkromhout commented
Hi, @woodgear - we would like to merge your PR - can you please make the requested changes? If you cannot, we make have to close it unmerged. Thanks.

2022-01-14 14:49 UTC, bridgetkromhout commented
Hi, @woodgear - we are going to close this PR unmerged for now. Please re-open with the requested changes if desired! Thanks.

2022-01-14 14:49 UTC, closed without merging