Add hook annotation to output hook logs to client on error
helm/helm-www pull request #1242
Opened 2021-11-26 11:56 UTC by Bez625

Documentation to accompany https://github.com/helm/helm/pull/10309

Signed-off-by: Chris Berry <bez625@gmail.com>

2021-12-02 21:04 UTC, bridgetkromhout commented
Thanks for submitting a docs update! We review docs updates after the related code changes are approved, and merge when the code changes are released.

2021-12-03 10:17 UTC, Bez625 commented
Thanks @bridgetkromhout - we have been pushing to get the code changes reviewed. If there is anything we can do to help speed that up please let us know!

2025-01-15 18:38 UTC, scottrigby approved these changes
LGTM 👍 
⚠️ Do not merge until implementation PR approval/merge, and release (would go into the next MINOR release. Since 3.17.0 is being cut today, this would go into 3.18.0, scheduled for May 14)

2025-02-05 23:01 UTC, scottrigby requested changes
Making a demo for this, I ran into some issues that had to be fixed for the example to work.

2025-02-22 07:51 UTC, Bez625 commented
> Actually, when making a demo for this, I ran into some issues that had to be fixed for the example to work.

Thanks @scottrigby - I've updated with your suggestions.

2025-11-13 15:17 UTC, bpartridge commented
Re-bumping this as this is an oft-requested feature, and with Helm 4 now out (congrats all!) it should be documented! (Arguably should have been part of changelog, I'm not sure what the policy is on retconning changelogs, but at least we can get documentation up to date.)

Also worth noting this has been backported to Helm 3 via https://github.com/helm/helm/pull/30570 - this should be reflected in documentation here!

2026-03-08 13:51 UTC, TerryHowe requested changes
Thanks for adding documentation for `helm.sh/hook-output-log-policy` — this is a useful feature and the overall structure is clear.

Two critical issues need fixing before merge:
1. **`chart_tests.md`**: The new annotation is missing the `helm.sh/` prefix, and the line break introduced a stray `- ` bullet that breaks the sentence. See inline comment.

The `charts_hooks.md` changes look good overall. The other inline comments are suggestions for polish (trailing whitespace, a comment on `backoffLimit: 0`, and minor prose improvements).

2026-03-08 13:51 UTC, TerryHowe commented on content/en/docs/topics/chart_tests.md
> +- may be used with test resources.
**Critical:** Two issues on these lines:

1. **Missing `helm.sh/` prefix** — the annotation should be `` `helm.sh/hook-output-log-policy` `` to match the full qualified names used for the other two annotations on the same line.

2. **Broken sentence** — the `- ` at the start of line 105 creates a stray list item, splitting the sentence incorrectly. The text should remain part of the same sentence continuation from the previous line.

Suggested fix:
```markdown
- A test is a [Helm hook](/docs/charts_hooks/), so annotations like
  `helm.sh/hook-weight`, `helm.sh/hook-delete-policy` and `helm.sh/hook-output-log-policy`
  may be used with test resources.
```

2026-03-08 13:51 UTC, TerryHowe commented on content/en/docs/topics/charts_hooks.md
> +  backoffLimit: 0
**Suggestion:** Trailing whitespace on this line. Also, a brief inline comment explaining why `backoffLimit: 0` is needed would help readers understand its purpose in the context of this feature.

```yaml
  backoffLimit: 0  # prevent retries so hook logs are captured on first failure
```

2026-03-08 13:51 UTC, TerryHowe commented on content/en/docs/topics/charts_hooks.md
> +`helm.sh/hook-output-log-policy` annotation](#hook-output-log-policies) to the
**Suggestion:** Minor prose nits:
- "pre or post requisite" → "pre- or post-requisite" (or just "prerequisite/postrequisite actions")
- "helm client" → "Helm client" (capitalize as a proper noun, consistent with rest of docs)
- Trailing space at end of lines 113 and 114

Suggested rewrite:
```
When Pod and Job resources are created as hooks they are often used to perform
pre- or post-requisite actions. In these cases it is often useful to surface the
hook's output to the Helm client. To achieve this you can [add a custom
`helm.sh/hook-output-log-policy` annotation](#hook-output-log-policies) to the
template.
```

2026-03-08 13:52 UTC, TerryHowe commented
Conflicts as well. Thanks if you get the time to fix this.

2026-07-08 00:22 UTC, closed without merging