blog declarative tools update
helm/helm-www pull request #1331
Opened 2022-07-07 22:53 UTC by scottrigby

@bridgetkromhout requesting your review as a follow-up to #1310.
Closes #1310

@mattfarina requesting your review since you're co-author.

- Flux supports Helm OCI repository as a chart source
- Includes complete commit from #1310 by @zhhray
- Clarify the current state of the blog post is now the most recent update if there is one. To handle this, I modified the blog templates to show the last updated date for any blog posts that were updated on any day after the original post.

# So, style…

### Here's how the list view looks - comparing a post that was updated vs one that wasn't:
<img width="879" alt="Screen Shot 2022-07-07 at 7 01 38 PM" src="https://user-images.githubusercontent.com/407675/177885402-dfc0973a-95c4-468c-b018-26a88cd2f899.png">
 
### Here's how the two above compare in a single blog page view:

Not updated:
<img width="842" alt="Screen Shot 2022-07-07 at 7 04 54 PM" src="https://user-images.githubusercontent.com/407675/177885729-250250c8-7f8b-4ccd-a076-ecd7d2517c1d.png">

Updated:
<img width="807" alt="Screen Shot 2022-07-07 at 7 04 20 PM" src="https://user-images.githubusercontent.com/407675/177885674-c23306a2-c28e-40e4-834f-ddb652c8968a.png">

2022-07-07 22:59 UTC, scottrigby commented on themes/helm/layouts/blog/list.html
> +              {{ if and (ne $lastmod $date) (gt .Lastmod .Date) }}
A note on why: the first condition checks that the date strings aren’t equal (to the day). The second checks the updated timestamp is greater than when it was posted.

2022-07-08 04:54 UTC, sabre1041 requested changes
Looks good. a couple minor items

2022-07-08 04:54 UTC, sabre1041 commented on content/en/blog/2022-04-19-tools-to-manage-helm-declaratively.md
> +[^7]: Terraform Helm provider has [some issues](https://github.com/hashicorp/terraform-provider-helm/issues/683) with Helm hooks and wait configurations.
The use of "some issues" makes it appear as there are/might be multiple to contend with. Only one issue is identified here

2022-07-08 04:54 UTC, sabre1041 commented on content/en/blog/2022-04-19-tools-to-manage-helm-declaratively.md
> +[^8]: Orkestra leverages Flux Helm Controller to reconcile the releases. Now that a full implementation is released in Flux, Orkestra is unblocked from supporting OCI. See [#411 (comment)](https://gi
```suggestion
[^8]: Orkestra leverages the Flux Helm Controller to reconcile the releases. Now that a full implementation is released in Flux, Orkestra is unblocked from supporting OCI. See [#411 (comment)](https://github.com/Azure/orkestra/issues/411#issuecomment-972571866) and [#411 (comment)](https://github.com/Azure/orkestra/issues/411#issuecomment-1178259373).
```

2022-11-01 08:52 UTC, zhhray commented
@scottrigby hi, is this pr ready to merge?

2023-04-15 03:49 UTC, angellk commented
@scottrigby could you resolve the conversations and get ready to merge? or should this be closed?

2025-01-31 16:45 UTC, scottrigby commented
I'm going to close this for now. But the code is useful if we ever want to add the ability to clearly show that a past blog post has been updated for some important reason.

2025-01-31 16:45 UTC, closed without merging