Chore: update docs to highlight repo URL
helm/helm-www pull request #1544
Opened 2024-01-16 02:08 UTC by thisisobate

Fixes #555

2024-10-07 20:14 UTC, mattfarina requested changes
There is a change that needs to be made here to make this work as intended.

2024-10-07 20:14 UTC, mattfarina commented on content/en/docs/intro/using_helm.md
> +
`helm search hub` exposes the URL to the location on artifacthub.io but not the actual Helm repo. On `helm search hub` you need to add the flag `--list-repo-url` to get that information. This flag needs to be documented to get the right URL to use with `helm repo add`

2024-10-08 14:17 UTC, thisisobate commented
@mattfarina Added the necessary changes. 
Feel free to take a look

2024-10-17 12:24 UTC, mattfarina approved these changes

2024-10-17 12:25 UTC, merged