[uk] add translation Go SDK and examples documentation
helm/helm-www pull request #1661
Opened 2024-11-29 18:42 UTC by Andygol

This PR contains the latest documentation updates translated into Ukrainian.

2025-01-10 22:55 UTC, scottrigby requested changes
@Andygol amazing, thanks! Some suggestions — you'll notice 2 repeating patterns for suggestions here. Thanks!

2025-01-11 14:51 UTC, Andygol commented on content/uk/docs/community/developers.md
> +Єдине виключення: [вивід CLI Helm (англійською)](/docs/helm/) генеруються безпосередньо з бінарного файлу `helm`. Дивіться [Оновлення довідкових документів CLI Helm](https://github.com/helm/helm-www#
It doesn't necessary to explicitly add language code as link decorator do it under the hood. You may see here (https://deploy-preview-1661--helm-merge.netlify.app/uk/docs/community/developers/#writing-documentation) that the link has been converted into (https://deploy-preview-1661--helm-merge.netlify.app/uk/docs/helm/)

2025-01-11 14:53 UTC, Andygol commented on content/uk/docs/community/release_checklist.md
> +Розділ документації на сайті [Helm](/docs) містить версії Helm. Необхідно оновити на сайті версії для major, minor і patch. Також потрібно оновити дату наступного minor релізу.
It doesn't necessary to explicitly add language code as link decorator do it under the hood

2025-01-11 14:54 UTC, Andygol commented on content/uk/docs/faq/troubleshooting.md
> +**Примітка:** Розробники Helm рекомендують міграцію на підтримувану версію Helm. Helm v2.17.0 був останнім випуском Helm v2; Helm v2 більше не підтримується з листопада 2020 року, як детально описано
It doesn't necessary to explicitly add language code as link decorator do it under the hood

2025-01-11 14:55 UTC, Andygol commented on content/uk/docs/intro/install.md
> +Після успішного встановлення клієнта Helm, ви можете перейти до використання Helm для керування чартами та [додавання стабільного репозиторію чартів](/docs/intro/quickstart/#initialize-a-helm-chart-r
It doesn't necessary to explicitly add language code as link decorator do it under the hood

2025-01-11 14:58 UTC, Andygol commented on content/uk/docs/community/history.md
> +Helm є [дипломованим](/blog/celebrating-helms-cncf-graduation/) [проєктом CNCF](https://www.cncf.io/projects/).
The case without `baseUR` works pretty well; link decorator is on duty 😉

2025-01-11 15:01 UTC, Andygol commented on content/uk/docs/faq/troubleshooting.md
> +Релізи Helm раніше були доступні за адресою <https://storage.googleapis.com/kubernetes-helm/>. Як пояснюється в ["Announcing get.helm.sh"](/blog/get-helm-sh/), офіційне місце розташування змінилося у
The same as previous, link decorator works 🎸 as expected re-addressing to English blog post. See here https://deploy-preview-1661--helm-merge.netlify.app/uk/docs/faq/troubleshooting/#installing-tiller-stopped-working-and-access-is-denied

2025-01-11 15:04 UTC, Andygol commented on content/uk/docs/glossary/_index.md
> +Реєстр чартів Helm є системою зберігання та розподілу на основі [OCI](https://opencontainers.org/about/overview/), яка використовується для розміщення та обміну пакетами чартів Helm. Для отримання до
It doesn't necessary to explicitly add language code as link decorator do it under the hood. Check it here https://deploy-preview-1661--helm-merge.netlify.app/uk/docs/glossary/#chart-registry-oci-based-registry

2025-01-11 15:07 UTC, Andygol commented on content/uk/docs/howto/chart_releaser_action.md
> +щоб отримати останні версії пакетів. Потім ви можете виконати `helm search repo <alias>`, щоб побачити чарти.
🙇

2025-01-11 15:08 UTC, Andygol commented on content/uk/docs/intro/quickstart.md
> +Дивіться [Політику підтримки версій Helm](/docs/topics/version_skew/) щодо максимальної підтримуваної різниці версій між Helm і Kubernetes.
It doesn't necessary to explicitly add language code as link decorator do it under the hood. See https://deploy-preview-1661--helm-merge.netlify.app/uk/docs/intro/quickstart/#install-kubernetes-or-have-access-to-a-cluster

2025-01-11 15:17 UTC, Andygol commented
@scottrigby
Thank you for reviewing this PR. In most cases, except for one (where the code is not handled by the link decorator), it is not necessary to explicitly add language code, as the link decorator does it implicitly by adding language code or by using the default page in English, in the absence of translation. 

I look forward to the approval of this PR as soon as possible. 🤝

2025-01-11 21:01 UTC, scottrigby commented on content/uk/docs/community/history.md
> +Helm є [дипломованим](/blog/celebrating-helms-cncf-graduation/) [проєктом CNCF](https://www.cncf.io/projects/).
you are right. Thanks, I didn't realize this

2025-01-11 21:02 UTC, scottrigby approved these changes
Thanks @Andygol – TIL about link decorator for translations. LGTM 👍

2025-01-14 22:33 UTC, scottrigby commented
I re-ran the deploy preview manually, and it succeeded. Here's the link: https://6786e519f9650418cae40d51--helm-merge.netlify.app

2025-01-15 16:55 UTC, merged