Translate /docs/helm/helm.md in Korean
helm/helm-www pull request #802
Opened 2020-09-07 07:14 UTC by bluefriday

Signed-off-by: bluefriday <bluefriday86@gmail.com>

Translate /docs/helm/helm.md in Korean
- https://helm.sh/docs/helm/helm/

2020-09-07 07:18 UTC, bluefriday commented
@singlemocha helm 명령어에 대하여 한글화 작업 수행 했습니다. 부족한 부분이 많은데, 검토 부탁드립니다.

2020-09-08 17:19 UTC, singlemocha requested changes
수고 많으셨습니다! Helm과 release 는 전체적으로 확인하여 번역이 필요할것 같습니다. 다른 파일에서 다 번역했거든요.

2020-09-08 17:19 UTC, singlemocha commented on content/ko/docs/helm/helm.md
> +      --registry-config string           레지스트리 구성 파일에 대한 경로 (default "~/.config/helm/registry.json")
레지스트리 구성 파일에 대한 경로 (기본값 "~/.config/helm/registry.json")

2020-09-08 17:19 UTC, singlemocha commented on content/ko/docs/helm/helm.md
> +      --repository-cache string          캐시된 저장소 색인이 포함된 파일의 경로 (default "~/snap/code/common/.cache/helm/repository")
캐시된 저장소 색인이 포함된 파일의 경로 (기본값 "~/snap/code/common/.cache/helm/repository")

2020-09-08 17:19 UTC, singlemocha commented on content/ko/docs/helm/helm.md
> +      --repository-config string         저장소 이름 및 URL 을 포함하는 파일 경로 (default "~/.config/helm/repositories.yaml")
저장소 이름 및 URL 을 포함하는 파일 경로 (기본값 "~/.config/helm/repositories.yaml")

2020-09-08 17:19 UTC, singlemocha commented on content/ko/docs/helm/helm.md
> +      --vmodule moduleSpec               파일로 필터링 된 로깅을 위한 패턴=N 설정의, 쉼표로 구분된 리스트
파일로 필터링 된 로깅을 위한 패턴=N 설정의 쉼표로 구분된 리스트

2020-09-08 17:19 UTC, singlemocha commented on content/ko/docs/helm/helm.md
> +### 함께 보기
다른 파일에서 See Also를 '참조'로 번역해서 일관성을 위해 참조로 번역하면 어떨까요?

2020-09-08 17:19 UTC, singlemocha commented on content/ko/docs/helm/helm.md
> +* [helm completion](/docs/helm/helm_completion)	 - 지정된 셸(bash or zsh)에 대한 자동 완성 스크립트 생성
지정된 셸(bash 또는 zsh)에 대한 자동 완성 스크립트 생성

2020-09-08 17:19 UTC, singlemocha commented on content/ko/docs/helm/helm.md
> +* [helm env](/docs/helm/helm_env)	 - 클라이언트 환경 정보
헬름 클라이언트 환경 정보

2020-09-08 17:19 UTC, singlemocha commented on content/ko/docs/helm/helm.md
> +* [helm version](/docs/helm/helm_version)	 - 클라이언트
클라이언트 버전 정보 표시

2020-09-08 17:19 UTC, singlemocha commented on content/ko/docs/helm/helm.md
> +* [helm version](/docs/helm/helm_version)	 - 클라이언트
release를 릴리즈로 번역해야 할것 같습니다.

2020-09-10 04:22 UTC, bluefriday commented on content/ko/docs/helm/helm.md
> +title: "Helm"
네 해당 표현에 대하여 일괄 변경하겠습니다.

2020-09-10 04:22 UTC, bluefriday commented on content/ko/docs/helm/helm.md
> +쿠버네티스를 위한 Helm 패키지 매니저.
네 맞춤표 생략하겠습니다.

2020-09-10 04:23 UTC, bluefriday commented on content/ko/docs/helm/helm.md
> +Helm 에 대한 공통된 동작:
'일반적으로 사용되는 헬름 작업' 으로 변경하겠습니다.

2020-09-10 04:24 UTC, bluefriday commented on content/ko/docs/helm/helm.md
> +- helm list:      차트 release 리스트 표시
해당 표현에 대하여도 일괄로 '릴리즈'로 변경하였습니다.

2020-09-10 04:25 UTC, bluefriday commented on content/ko/docs/helm/helm.md
> +| Name                               | Description                                                                       |
리뷰해주신 내용으로 변경하였습니다.

2020-09-10 04:27 UTC, bluefriday commented on content/ko/docs/helm/helm.md
> +| $KUBECONFIG                        | 대체 설정 파일 지정 (기본값 "~/.kube/config")                                              |
네 말씀해주신 부분이 더 직관적인 것 같습니다. 가이드해주신대로 변경하겠습니다.

2020-09-10 04:28 UTC, bluefriday commented on content/ko/docs/helm/helm.md
> +      --kube-context string              kubeconfig 컨텍스트의 문자열 이름
수정하였습니다.

2020-09-10 04:29 UTC, bluefriday commented on content/ko/docs/helm/helm.md
> +      --registry-config string           레지스트리 구성 파일에 대한 경로 (default "~/.config/helm/registry.json")
default 항목에 대하여 일괄 '기본값' 으로 변경하였습니다.

2020-09-10 04:30 UTC, bluefriday commented on content/ko/docs/helm/helm.md
> +      --vmodule moduleSpec               파일로 필터링 된 로깅을 위한 패턴=N 설정의, 쉼표로 구분된 리스트
쉼표 제거하였습니다.

2020-09-10 04:30 UTC, bluefriday commented on content/ko/docs/helm/helm.md
> +### 함께 보기
해당 표현으로 변경하였습니다. 향후 '참조'로 사용하겠습니다.

2020-09-10 04:31 UTC, bluefriday commented on content/ko/docs/helm/helm.md
> +* [helm completion](/docs/helm/helm_completion)	 - 지정된 셸(bash or zsh)에 대한 자동 완성 스크립트 생성
or을 '또는' 으로 변경하였습니다.

2020-09-10 04:32 UTC, bluefriday commented on content/ko/docs/helm/helm.md
> +* [helm env](/docs/helm/helm_env)	 - 클라이언트 환경 정보
'헬름' 추가하였습니다.

2020-09-10 04:33 UTC, bluefriday commented on content/ko/docs/helm/helm.md
> +* [helm version](/docs/helm/helm_version)	 - 클라이언트
해당 내용 추가하였습니다.

2020-09-10 04:34 UTC, bluefriday commented on content/ko/docs/helm/helm.md
> +      --alsologtostderr                  표준 오류를 로그 및 파일로 표시
해당 내용에 대해 고민을 했었는데, 말씀해주신 표현이 더 적절한 것 같습니다. 도움주셔서 감사합니다.

2020-09-10 04:35 UTC, bluefriday commented
> 수고 많으셨습니다! Helm과 release 는 전체적으로 확인하여 번역이 필요할것 같습니다. 다른 파일에서 다 번역했거든요.

@singlemocha 세세한 부분까지 리뷰해주셔서 감사합니다. 가이드해주신 부분은 향후 다른 번역에도 고려하겠습니다.

2020-09-10 07:58 UTC, jmnote reviewed
릴리즈 → 릴리스

https://kubernetes.io/ko/docs/contribute/localization_ko/#%ED%95%9C%EA%B8%80%ED%99%94-%EC%9A%A9%EC%96%B4%EC%A7%91

2020-09-10 07:58 UTC, jmnote commented on content/ko/docs/helm/helm.md
> +* [helm upgrade](/docs/helm/helm_upgrade)	 - 릴리즈 업그레이드
```suggestion
* [helm get](/docs/helm/helm_get)	 - 명명된 릴리스의 확장 정보 다운로드
* [helm history](/docs/helm/helm_history)	 - 릴리스 기록 가져오기
* [helm install](/docs/helm/helm_install)	 - 차트 설치
* [helm lint](/docs/helm/helm_lint)	 - 차트에서 발생 가능한 이슈 검사
* [helm list](/docs/helm/helm_list)	 - 릴리스 목록
* [helm package](/docs/helm/helm_package)	 - 차트 디렉토리를 차트 아카이브로 패키징
* [helm plugin](/docs/helm/helm_plugin)	 - Helm 플러그인 설치, 조회, 제거
* [helm pull](/docs/helm/helm_pull)	 - 저장소에서 차트를 다운로드하고 (선택적으로) 로컬디렉터리에 압축 해제
* [helm repo](/docs/helm/helm_repo)	 - 차트 저장소의 추가, 조회, 제거, 업데이트 및 색인 생성
* [helm rollback](/docs/helm/helm_rollback)	 - 릴리스를 이전 버전으로 롤백
* [helm search](/docs/helm/helm_search)	 - 차트에서 키워드 검색
* [helm show](/docs/helm/helm_show)	 - 차트 정보 표시
* [helm status](/docs/helm/helm_status)	 - 명명된 릴리스의 상태 표시
* [helm template](/docs/helm/helm_template)	 - 로컬에서 템플릿 렌더링
* [helm test](/docs/helm/helm_test)	 - 릴리스 테스트 수행
* [helm uninstall](/docs/helm/helm_uninstall)	 - 릴리스 제거
* [helm upgrade](/docs/helm/helm_upgrade)	 - 릴리스 업그레이드
```

2020-09-10 07:58 UTC, jmnote commented on content/ko/docs/helm/helm.md
> +- helm list:      차트 릴리즈 리스트 표시
```suggestion
- helm list:      차트 릴리스 리스트 표시
```

2020-09-11 01:15 UTC, jmnote commented
/lgtm

2020-09-16 02:05 UTC, markruler commented on content/ko/docs/helm/helm.md
> +| $XDG_CACHE_HOME                    | 캐시된 파일을 저장할 대체 위치를 지정.                                                          |
#818 환경 변수명과 아래쪽 설명이 변경되었습니다.
아직 open 상태라 리뷰드려봅니다.

2020-09-16 09:03 UTC, markruler requested changes

2020-09-16 10:03 UTC, bluefriday commented on content/ko/docs/helm/helm.md
> +- 데이터는 $XDG_DATA_HOME/helm 에 저장
리뷰 해주셔서 감사합니다. 해당 내용으로 변경하여 commit 하겠습니다 :D

2020-09-18 04:34 UTC, bridgetkromhout commented on content/ko/docs/helm/helm.md
> +      --repository-cache string          캐시된 저장소 색인이 포함된 파일의 경로 (기본값 "~/snap/code/common/.cache/helm/repository")
Ah! This is where you were getting that. Well, I'll figure out why it is only in this one place in the English. No change for now.

2020-09-18 04:36 UTC, bridgetkromhout approved these changes
LGTM!

2020-09-18 04:36 UTC, merged