Add Kubernetes client logging to FAQ
helm/helm-www pull request #867
Opened 2020-09-25 18:45 UTC by adamreese

ref: https://github.com/helm/helm/pull/8067

2020-09-26 01:51 UTC, bridgetkromhout approved these changes

2020-09-28 08:57 UTC, hickeyma requested changes
@adamreese Thanks for pushing the related doc PR. Looks good bar small change inline.

2020-09-28 08:57 UTC, hickeyma commented on content/en/docs/faq/_index.md
> +
How about adding the following for more clarity above the example?

"For example: "

2020-09-28 17:41 UTC, hickeyma approved these changes
LGTM, thanks @adamreese

2020-09-29 14:50 UTC, mattfarina approved these changes
lgtm

2020-09-29 14:51 UTC, merged