[ko] Translate community/developer-guide in korean
helm/helm-www pull request #946
Opened 2020-11-11 06:21 UTC by bluefriday

Signed-off-by: bluefriday <bluefriday86@gmail.com>

[ko] Translate community/developer-guide in korean

2020-11-11 06:21 UTC, bluefriday commented
https://github.com/helm/helm-www/issues/945

2020-11-24 03:01 UTC, jangdm reviewed
띄어쓰기, 오타 수정했습니다.

2020-11-25 08:54 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +그렇지 않으면 `build`가 관련 패키지를 찾지 못 한다.
의견 주신 내용으로 변경하겠습니다.

2020-11-25 08:54 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +모든 테스트를 실행하려면 (`vendor /` 에 대한 테스트를 실행하지 않고) `make test` 를 실행합니다.
의견 주신 내용으로 변경하겠습니다.

2020-11-25 08:55 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +`bin / helm` 에 배치합니다.
의견 주신 내용으로 변경하겠습니다.

2020-11-25 08:55 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +- 개별 프로그램은 `cmd /`에 위치
의견 주신 내용으로 변경하겠습니다.

2020-11-25 08:55 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +  대부분은 CI/\CD 파이프 라인에서 사용
의견 주신 내용으로 변경하겠습니다.

2020-11-25 23:52 UTC, singlemocha commented
LGTM

2020-11-26 05:23 UTC, sunminjeon reviewed
문맥을 조금 수정해보았습니다.

2020-11-26 05:23 UTC, sunminjeon commented on content/ko/docs/community/developers.md
> +이 가이드에서는 Helm에서 개발하기 위해 환경을 설정하는 방법을 설명한다.
```suggestion
이 가이드에서는 Helm을 개발하기 위해 환경을 설정하는 방법을 설명한다. 
```
문맥을 조금 수정하였습니다.

2020-11-26 05:23 UTC, sunminjeon commented on content/ko/docs/community/developers.md
> +Helm 3 이후로 문서는 자체 저장소로 이동되었다.
```suggestion
Helm 3 이후의 문서는 자체 저장소로 이동되었다. 
```
문맥을 수정해보았습니다.

2020-11-26 05:23 UTC, sunminjeon commented on content/ko/docs/community/developers.md
> +  이 섹션에서 영감을 받았다.
```suggestion
- [Deis 
  가이드라인](https://github.com/deis/workflow/blob/master/src/contributing/submitting-a-pull-request.md)은 
  이 섹션에 영감을 줬다.
```
문맥을 수정하였습니다.

2020-11-26 08:19 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +이 가이드에서는 Helm에서 개발하기 위해 환경을 설정하는 방법을 설명한다.
의견 주신 내용으로 변경하겠습니다.

2020-11-26 08:19 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +Helm 3 이후로 문서는 자체 저장소로 이동되었다.
의견 주신 내용으로 변경하겠습니다.

2020-11-26 08:19 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +  이 섹션에서 영감을 받았다.
의견 주신 내용으로 변경하겠습니다.

2020-11-26 08:29 UTC, bluefriday commented
@jmnote 리뷰 감사합니다. 의견 주신 내용으로 변경하였습니다.

2020-11-30 02:27 UTC, jmnote commented
https://raw.githubusercontent.com/helm/helm-www/master/content/en/docs/community/developers.md

2020-12-01 01:12 UTC, jmnote requested changes
일부 수정해봤습니다.

2020-12-01 01:40 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +이 가이드에서는 Helm을 개발하기 위해 환경을 설정하는 방법을 설명한다.
의견 주신 내용으로 변경하겠습니다.

2020-12-01 01:40 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +- kubectl 이 사용가능한 쿠버네티스 클러스터(선택사항)
의견 주신 내용으로 변경하겠습니다.

2020-12-01 01:41 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +`bin/helm` 에 배치합니다.
의견 주신 내용으로 변경하겠습니다.

2020-12-01 01:41 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +모든 테스트를 실행하려면 (`vendor/` 에 대한 테스트를 실행하지 않고) `make test` 를 실행합니다.
의견 주신 내용으로 변경하겠습니다.

2020-12-01 01:41 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +헬름을 로컬에서 실행하기 위해 사용자는 `bin/helm` 을 실행한다.
의견 주신 내용으로 변경하겠습니다.

2020-12-01 01:41 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +- 헬름은 macOS 및 Alpine을 포함한 대부분의 Linux 배포에서 실행되는 것으로 알려져 있다.
의견 주신 내용으로 변경하겠습니다.

2020-12-01 01:42 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +고품질의 오픈 소스 코드를 구축하는 것이다.
의견 주신 내용으로 변경하겠습니다.

2020-12-01 01:42 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +주요 기여 가이드를 읽고 숙지했는지 확인하도록 한다.
의견 주신 내용으로 변경하겠습니다.

2020-12-01 01:52 UTC, bluefriday commented
@jmnote 리뷰해주신 부분에 대하여 수정하였습니다.

2020-12-04 06:49 UTC, jmnote reviewed
일부 수정해봤습니다.

2020-12-04 06:49 UTC, jmnote commented on content/ko/docs/community/developers.md
> +## 헬릉 구축하기
```suggestion
## 헬름 빌드하기
```

2020-12-04 06:49 UTC, jmnote commented on content/ko/docs/community/developers.md
> +우리는 프로그램을 구축하기 위해 Make를 사용한다. 시작하는 가장 간단한 방법은 다음과 같다.
```suggestion
프로그램을 빌드하기 위해 Make를 사용한다. 시작하는 가장 간단한 방법은 다음과 같다.
```

2020-12-04 06:49 UTC, jmnote commented on content/ko/docs/community/developers.md
> +  [포맷](https://github.com/golang/go/wiki/CodeReviewComments) 기사
```suggestion
- Go 위키에서 볼 수 있는 훌륭한 
  [포맷](https://github.com/golang/go/wiki/CodeReviewComments) 글
```

2020-12-04 06:53 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +## 헬릉 구축하기
의견 주신 내용으로 변경하겠습니다.

2020-12-04 06:54 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +우리는 프로그램을 구축하기 위해 Make를 사용한다. 시작하는 가장 간단한 방법은 다음과 같다.
의견 주신 내용으로 변경하겠습니다.

2020-12-04 06:54 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +  [포맷](https://github.com/golang/go/wiki/CodeReviewComments) 기사
의견 주신 내용으로 변경하겠습니다.

2020-12-04 07:33 UTC, bluefriday commented
> 일부 수정해봤습니다.


@jmnote 의견주신 부분 반영하였습니다.

2020-12-10 03:37 UTC, jmnote reviewed
일부 수정해봤습니다.

2020-12-10 03:37 UTC, jmnote commented on content/ko/docs/community/developers.md
> +- 깃(Git)
```suggestion
- Git
```

2020-12-10 03:37 UTC, jmnote commented on content/ko/docs/community/developers.md
> +깃 커밋 메세지의 경우, 우리는 [유의적 커밋 메세지](https://karma-runner.github.io/0.13/dev/git-commit-msg.html)를
```suggestion
Git 커밋 메세지의 경우, 우리는 [유의적 커밋 메세지](https://karma-runner.github.io/0.13/dev/git-commit-msg.html)를 
```

2020-12-10 03:37 UTC, jmnote commented on content/ko/docs/community/developers.md
> +### 깃 관례
```suggestion
### Git 관례
```

2020-12-10 03:37 UTC, jmnote commented on content/ko/docs/community/developers.md
> +헬름 2 릴리스가 잘려나간 기본 브랜치이다.
```suggestion
버전 제어 시스템으로는 Git을 사용한다. `master` 브랜치는 현재 개발 
예정 브랜치의 홈 브랜치이다. 릴리스는 태그가 지정되며, 
사용자가 헬름 v2 용 패치 작업을 하는 경우 `dev-v2` 브랜치는 
헬름 2 릴리스가 잘려나간 기본 브랜치이다.
```

2020-12-10 03:37 UTC, jmnote commented on content/ko/docs/community/developers.md
> +이를 위한 작업 흐름은 다음과 같습니다.
```suggestion
이를 위한 작업 흐름은 다음과 같다.
```

2020-12-10 03:37 UTC, jmnote commented on content/ko/docs/community/developers.md
> +   `git clone` 으로 `github.com/helm/helm` 레포지터리를 복제
```suggestion
1. `$GOPATH/src` 디렉토리로 이동한 후에, `mkdir helm.sh; cd helm.sh` 을 수행하고,
   `git clone` 으로 `github.com/helm/helm` 레포지터리를 복제한다.
```

2020-12-10 03:37 UTC, jmnote commented on content/ko/docs/community/developers.md
> +2. 해당 레포지터리를 깃헙 계정으로 포크
```suggestion
2. 해당 레포지터리를 GitHub 계정으로 포크한다.
```

2020-12-10 03:37 UTC, jmnote commented on content/ko/docs/community/developers.md
> +3. 레포지터리를 `$GOPATH/src/helm.sh/helm` 에 대한 원격 레포지터리로 추가
```suggestion
3. 레포지터리를 `$GOPATH/src/helm.sh/helm` 에 대한 원격 레포지터리로 추가한다.
```

2020-12-10 03:37 UTC, jmnote commented on content/ko/docs/community/developers.md
> +   작업을 수행
```suggestion
4. 새로운 작업 브랜치를 만들고(`git checkout -b feat/my-feature`) 해당 브랜치에서
   작업을 수행한다.
```

2020-12-10 03:37 UTC, jmnote commented on content/ko/docs/community/developers.md
> +   새로운 풀 리퀘스트를 생성
```suggestion
5. 리뷰를 위한 준비가 되면 브랜치를 GitHub으로 푸시한 다음 
   새로운 풀 리퀘스트를 생성한다.
```

2020-12-10 03:37 UTC, jmnote commented on content/ko/docs/community/developers.md
> +  이 섹션에 영감을 줬다.
```suggestion
- 이 섹션은 [Deis 
  가이드라인](https://github.com/deis/workflow/blob/master/src/contributing/submitting-a-pull-request.md)에서 영감을 받아 작성되었다.
```

2020-12-10 03:37 UTC, jmnote commented on content/ko/docs/community/developers.md
> +스타일 적합성을 테스트 하려는 경우 `make test-style` 을 실행하라.
```suggestion
스타일 적합성을 테스트하려는 경우 `make test-style` 을 실행하자.
```

2020-12-10 03:37 UTC, jmnote commented on content/ko/docs/community/developers.md
> +되지 않은 것으로 간주한다.
```suggestion
`make test` 대상이 스타일 상의 이유로 실패하면 PR 은 병합할 준비가
되지 않은 것으로 간주한다.
```

2020-12-10 04:51 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +- 깃(Git)
의견 주신 내용으로 변경하겠습니다.

2020-12-10 04:51 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +깃 커밋 메세지의 경우, 우리는 [유의적 커밋 메세지](https://karma-runner.github.io/0.13/dev/git-commit-msg.html)를
의견 주신 내용으로 변경하겠습니다.

2020-12-10 04:51 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +### 깃 관례
의견 주신 내용으로 변경하겠습니다.

2020-12-10 04:51 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +헬름 2 릴리스가 잘려나간 기본 브랜치이다.
의견 주신 내용으로 변경하겠습니다.

2020-12-10 04:52 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +   작업을 수행
의견 주신 내용으로 변경하겠습니다.

2020-12-10 04:52 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +   새로운 풀 리퀘스트를 생성
의견 주신 내용으로 변경하겠습니다.

2020-12-10 04:52 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +  이 섹션에 영감을 줬다.
의견 주신 내용으로 변경하겠습니다.

2020-12-10 04:53 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +되지 않은 것으로 간주한다.
의견 주신 내용으로 변경하겠습니다.

2020-12-10 04:53 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +스타일 적합성을 테스트 하려는 경우 `make test-style` 을 실행하라.
의견 주신 내용으로 변경하겠습니다.

2020-12-10 04:53 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +   `git clone` 으로 `github.com/helm/helm` 레포지터리를 복제
의견 주신 내용으로 변경하겠습니다.

2020-12-10 04:53 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +2. 해당 레포지터리를 깃헙 계정으로 포크
의견 주신 내용으로 변경하겠습니다.

2020-12-10 04:54 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +3. 레포지터리를 `$GOPATH/src/helm.sh/helm` 에 대한 원격 레포지터리로 추가
의견 주신 내용으로 변경하겠습니다.

2020-12-10 05:01 UTC, bluefriday commented
@jmnote 추가로 의견 주신 부분에 대하여 반영하였습니다. 감사합니다~

2020-12-22 02:15 UTC, jmnote reviewed
일부 수정해봤습니다.

2020-12-22 02:15 UTC, jmnote commented on content/ko/docs/community/developers.md
> +- 헬름은 맥OS 및 Alpine을 포함한 대부분의 Linux 배포판에서 실행되는 것으로 알려져 있다.
```suggestion
- 헬름은 맥OS 및 Alpine을 포함한 대부분의 리눅스 배포판에서 실행되는 것으로 알려져 있다.
```

2020-12-22 02:15 UTC, jmnote commented on content/ko/docs/community/developers.md
> +변경 될 수 있다. 개발자는 종속성을 수동으로 관리하지
```suggestion
Go 종속성 관리는 유동적이며 Helm의 수명주기 동안 
변경될 수 있다. 개발자는 종속성을 수동으로 관리하지 
```

2020-12-22 02:15 UTC, jmnote commented on content/ko/docs/community/developers.md
> +_않는것을_ 권장한다. 대신 프로젝트의 `Makefile` 에
```suggestion
_않기를_ 권장한다. 대신 프로젝트의 `Makefile` 에 
```

2020-12-22 02:15 UTC, jmnote commented on content/ko/docs/community/developers.md
> +헬름 2 릴리스가 잘려나간 기본 브랜치이다.
```suggestion
헬름 2 릴리스가 분리된 기본 브랜치이다.
```

2020-12-22 02:15 UTC, jmnote commented on content/ko/docs/community/developers.md
> +- pkg/lint: 린트(lint) 패키지. 모든 패키지에 대하여 유사규칙을 따름
```suggestion
- pkg/lint: 린트(lint) 패키지. 어떤 패키지든 유사한 관례에 따르자.
```

2020-12-22 02:15 UTC, jmnote commented on content/ko/docs/community/developers.md
> +- `*`: 두 개 이상의 범위
```suggestion
- `*`: 두 개 이상의 스코프
```

2020-12-22 03:24 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +- 헬름은 맥OS 및 Alpine을 포함한 대부분의 Linux 배포판에서 실행되는 것으로 알려져 있다.
의견 주신 내용으로 반영하겠습니다.

2020-12-22 03:24 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +변경 될 수 있다. 개발자는 종속성을 수동으로 관리하지
의견 주신 내용으로 반영하겠습니다.

2020-12-22 03:24 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +_않는것을_ 권장한다. 대신 프로젝트의 `Makefile` 에
의견 주신 내용으로 반영하겠습니다.

2020-12-22 03:25 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +헬름 2 릴리스가 잘려나간 기본 브랜치이다.
의견 주신 내용으로 반영하겠습니다.

2020-12-22 03:25 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +- pkg/lint: 린트(lint) 패키지. 모든 패키지에 대하여 유사규칙을 따름
의견 주신 내용으로 반영하겠습니다.

2020-12-22 03:25 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +- `*`: 두 개 이상의 범위
의견 주신 내용으로 반영하겠습니다.

2020-12-22 03:40 UTC, bluefriday commented
@jmnote 의견 주신 내용으로 수정하였습니다. 감사합니다.

2020-12-22 06:32 UTC, jmnote reviewed
일부 수정해봤습니다.

2020-12-22 06:32 UTC, jmnote commented on content/ko/docs/community/developers.md
> +그렇지 않으면 `build`가 관련 패키지를 찾지 못한다.
```suggestion
심볼릭 링크이면 `build`가 관련 패키지를 찾지 못한다.
```

2020-12-22 06:32 UTC, jmnote commented on content/ko/docs/community/developers.md
> +`make test` 타겟을 실행하면 단위 테스트가 실행될 뿐만아니라 스타일 테스트도 실행된다.
```suggestion
`make test` 타겟을 실행하면 단위 테스트뿐만 아니라 스타일 테스트도 실행된다.
```

2020-12-22 06:32 UTC, jmnote commented on content/ko/docs/community/developers.md
> +  `cmd/` 내부의 코드는 라이브러리 재사용을 위해 미설계
```suggestion
  `cmd/` 내부의 코드는 라이브러리 재사용을 위해 설계되지는 않았다.
```

2020-12-22 06:32 UTC, jmnote commented on content/ko/docs/community/developers.md
> +- 개별 프로그램은 `cmd/`에 위치
```suggestion
- 개별 프로그램은 `cmd/`에 위치한다.
```

2020-12-22 06:32 UTC, jmnote commented on content/ko/docs/community/developers.md
> +- 공유 라이브러리는 `pkg/` 에 저장
```suggestion
- 공유 라이브러리는 `pkg/` 에 저장된다.
```

2020-12-22 06:32 UTC, jmnote commented on content/ko/docs/community/developers.md
> +- `scripts/` 디렉토리에는 여러 유틸리티 스크립트가 포함.
```suggestion
- `scripts/` 디렉토리에는 여러 유틸리티 스크립트가 들어 있다.
```

2020-12-22 06:32 UTC, jmnote commented on content/ko/docs/community/developers.md
> +  대부분은 CI/CD 파이프 라인에서 사용
```suggestion
  대부분 CI/CD 파이프라인에서 사용한다.
```

2020-12-22 06:32 UTC, jmnote commented on content/ko/docs/community/developers.md
> +`bin/helm` 로 옮긴다.
```suggestion
필요한 경우 먼저 의존성을 설치하고 `vendor/` 트리를 
다시 빌드하고 구성을 확인한다. 그런 다음 `helm` 을 컴파일하여 
`bin/helm` 로 옮긴다.
```

2020-12-22 06:32 UTC, jmnote commented on content/ko/docs/community/developers.md
> +Go 종속성 관리는 유동적이며 Helm의 수명주기 동안
```suggestion
Go 의존성 관리는 유동적이며 Helm의 수명주기 동안 
```

2020-12-22 06:32 UTC, jmnote commented on content/ko/docs/community/developers.md
> +변경될 수 있다. 개발자는 종속성을 수동으로 관리하지
```suggestion
변경될 수 있다. 개발자는 의존성을 수동으로 관리하지 
```

2020-12-22 06:58 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +- `scripts/` 디렉토리에는 여러 유틸리티 스크립트가 포함.
의견 주신 내용으로 변경하겠습니다.

2020-12-22 06:59 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +  대부분은 CI/CD 파이프 라인에서 사용
의견 주신 내용으로 반영하겠습니다.

2020-12-22 06:59 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +`bin/helm` 로 옮긴다.
의견 주신 내용으로 반영하겠습니다.

2020-12-22 07:16 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +Go 종속성 관리는 유동적이며 Helm의 수명주기 동안
의견 주신 내용으로 변경하였습니다.

2020-12-22 07:16 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +변경될 수 있다. 개발자는 종속성을 수동으로 관리하지
의견 주신 내용으로 변경하였습니다.

2020-12-22 07:16 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +그렇지 않으면 `build`가 관련 패키지를 찾지 못한다.
의견 주신 내용으로 변경하였습니다.

2020-12-22 07:16 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +`make test` 타겟을 실행하면 단위 테스트가 실행될 뿐만아니라 스타일 테스트도 실행된다.
의견 주신 내용으로 변경하였습니다.

2020-12-22 07:20 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +  `cmd/` 내부의 코드는 라이브러리 재사용을 위해 미설계
의견 주신 내용으로 변경하였습니다.

2020-12-22 07:20 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +- 개별 프로그램은 `cmd/`에 위치
의견 주신 내용으로 변경하였습니다.

2020-12-22 07:20 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +- 공유 라이브러리는 `pkg/` 에 저장
의견 주신 내용으로 변경하였습니다.

2020-12-22 07:28 UTC, bluefriday commented
@jmnote 추가로 의견 주신 내용에 대하여 반영하였습니다.

2020-12-22 08:26 UTC, jmnote reviewed
일부 수정해봤습니다.

2020-12-22 08:26 UTC, jmnote commented on content/ko/docs/community/developers.md
> +더 보기:
```suggestion
더 읽어보기:
```

2020-12-22 08:26 UTC, jmnote commented on content/ko/docs/community/developers.md
> +더 보기:
```suggestion
더 읽어보기:
```

2020-12-23 01:51 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +더 보기:
의견 주신 내용으로 변경하겠습니다.

2020-12-23 01:51 UTC, bluefriday commented on content/ko/docs/community/developers.md
> +더 보기:
의견 주신 내용으로 변경하겠습니다.

2020-12-23 02:15 UTC, jmnote commented
lgtm

2020-12-31 00:33 UTC, singlemocha approved these changes
LGTM

2021-01-05 20:22 UTC, bridgetkromhout approved these changes
Thanks!

2021-01-05 20:23 UTC, merged